### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DumbGameMaker**

### CODE REVIEW

**Comment by thedev132** [comment]
Keep some of the detailed instructions... Its not "npm run dev". Its "npm start". The detailed instructions are for people who are still learning how to code.

**Comment by DumbGameMaker** [comment]
﻿npm start is a shortcut to npm run start which runs the start script in package.json. The scripts are start (dev env), test (run tests), build (deploy), and eject (dont do this i beg of you) I meant start when i said dev my badSent from my iPhoneOn Oct 15, 2022, at 10:18 PM, The Developer ***@***.***> wrote:﻿
Keep some of the detailed instructions... Its not "npm run dev". Its "npm start". The detailed instructions are for people who are still learning how to code.

**Comment by thedev132** [comment]
Please change keep at least the "npm start" portion because some beginners might wonder how to run this and with the knowledge they don't have they'll fail

**Comment by DumbGameMaker** [comment]
Can you? Im tiiirrreeeddSent from my iPhoneOn Oct 15, 2022, at 11:01 PM, The Developer ***@***.***> wrote:﻿
Please change keep at least the "npm start" portion because some beginners might wonder how to run this and with the knowledge they don't have they'll fail

**Comment by thedev132** [comment]
Ok :)

**Pull request merged**
